### ISSUE TITLE
add flag to benchmark runner to activate or deactivate tracking

### ISSUE THREAD

**Issue by twollnik** [tjjordan/dyod22-memory-tracking#20]
add flag to benchmark runner to activate or deactivate tracking. One option: check benchmark runner to see how we can set flags (we need binary flag `memory_tracking`). this requires changes to the benchmark runner and the benchmark configuration and the cli config parser (see overview below). How to deactivate tracking if we use tracking_vector everywhere: return default memory resource in memory resource manager if tracking is deactivated.

**Comment by twollnik** [comment]
- [ ] flag in the benchmark runner to enable/disable the tracking
	+ [ ] `benchmark_runner.cpp` -> `cli_options.add_options()`
	+ [ ] `benchmark_config.hpp/cpp`
	+ [ ] `cli_config_parser.cpp`
